Add link to a specific product from all products list
vytcus/jadomaviciene pull request #6
Opened 2021-05-23 10:57 UTC by Jurgitaesu

Products.jsx faile pridėjau linką į productą pagal jo id. Taip pat į App.jsx failą įdėjau naują routą. Ar nieko nepamiršau?

2021-05-23 17:17 UTC, vytcus requested changes
All good, tik vieno pakeitimo reiktų.

2021-05-23 17:17 UTC, vytcus commented on eshop/src/App.jsx
> +          <Route exact path="/product">
Šiuo atveju path'as turėtų būti `/product/:id`

2021-05-24 06:06 UTC, Jurgitaesu commented on eshop/src/App.jsx
> +          <Route exact path="/product">
Teisingai, ačiū, pataisiau :)

2021-05-24 06:36 UTC, vytcus approved these changes

2021-05-27 18:06 UTC, merged